export const MAX_EPISODE_RELATIONSHIPS = 50;
export const MAX_AUDIO_MESSAGES_PER_USER_EPISODE = 50;
export const MAX_GAMBLING_ENTRIES_PER_EPISODE_UPDATE = 200;
export const MAX_EPISODE_SLUG_ATTEMPTS = 100;
