export const MAX_ASSIGNMENTS_PER_EPISODE = 50;
export const MAX_ASSIGNMENT_SLUG_ATTEMPTS = 100;
export const MAX_ASSIGNMENT_AUDIO_PAGE_SIZE = 50;
export const MAX_ASSIGNMENT_WORKBENCH_REVIEWS = 50;
export const MAX_ASSIGNMENT_WORKBENCH_GUESSES = 500;
export const MAX_ASSIGNMENT_WORKBENCH_WAGERS = 500;
