export const MAX_ROLE_CATALOG_SIZE = 50;
export const MAX_ROLES_PER_USER = 50;
export const MAX_SYLLABUS_ENTRIES_PER_USER = 100;
export const MAX_ROLE_MEMBERSHIPS_FOR_COUNT = 100;
export const MAX_ADMIN_MEMBERSHIPS_TO_INSPECT = 100;
